### PR TITLE
Release 4.4.0 with Resque 2 and redis-rb 4 support

### PR DESCRIPTION
**Pull request by jeremy**
~~Concerned that CI is testing against Resque 2 only, though.~~ #668

### CODE REVIEW

**Comment by jeremy** [comment]
```
$ gem owner resque-scheduler
Owners for gem: resque-scheduler
- bvandenbos@gmail.com
- dan@meatballhat.com
- ryan@yaauie.com
- sirup@sirupsen.com
- carson@reinke.co
```

Could one of y'all add @rafaelfranca and me (rafaelmfranca@gmail.com, jeremy@bitsweat.net) as owners so we can push releases?

/cc @carsonreinke @meatballhat @bvandenbos @yaauie @sirupsen

**Comment by carsonreinke** [comment]
@jeremy @rafaelfranca Added!

**Comment by paulomcnally** [comment]
:popcorn:

**Comment by paulomcnally** [comment]
Ping @jeremy @rafaelfranca

**Comment by jesperronn** [comment]
Note that this is not yet released. Work to be done:

* [ ] merge this PR
* [ ] publish version 4.4.0 on rubygems

This fixes #664 and #660 


Who is up for doing this?


/cc  @jeremy @rafaelfranca @carsonreinke @meatballhat @bvandenbos @yaauie @sirupsen

**Comment by jesperronn** [comment]
I just took a brief check on https://rubygems.org/gems/resque-scheduler, these changes are still not published. 

Maybe by mistake?

If you already published, could you please try again?  @jeremy @rafaelfranca @carsonreinke @meatballhat @bvandenbos @yaauie @sirupsen?

**Comment by jeremy** [comment]
@jesperronn Your vigor in tracking this is appreciated. I understand there's been a long wait. No further daily pings or mentioning all maintainers, please. We will release calmly in short order.

**Comment by jesperronn** [comment]
Thanks a lot for putting that extra effort into making the release. I really appreciate your work (which also made me eagerly push... sorry about being too pushy)

**Pull request merged**
