### PR TITLE
Fix before/after_schedule hooks not called when enqueued with config

### PR DESCRIPTION
**Pull request by jweir**

### CODE REVIEW

**Comment by codealchemy** [comment]
@iloveitaly hi there (I came across this after finding https://github.com/resque/resque-scheduler/issues/679)

I've got a scheduled job that needs to behave differently (not enqueue as configured, but kick off a separate variant of the job instead) depending on some runtime variables (eg. feature flag). The `before_schedule` hook seems to fit the bill, but doesn't work. These changes appear to fix it - I know it's been some time, but any chance this could move forward? Or should I address your requested changes on a separate PR?

**Comment by codealchemy** [comment]
@PatrickTulskie (seeing as this PR is quite out of date, wanted to get it back on the radar for consideration) 🙏

**Comment by PatrickTulskie** [comment]
@codealchemy Happy to get this one merged in since it does seem like it fixes an actual bug. It would be nice to get this branch rebased with master so that CI runs for it. I can handle the changelog updates when I do a release. Also possible that given how old this is, the PR might have to be adjusted. If you want to open a fresh PR and take over work on it, then go for it.

**Comment by codealchemy** [comment]
Thanks @PatrickTulskie - I've rebased these changes and opened https://github.com/resque/resque-scheduler/pull/792, failing builds there appear unrelated to the changes (and the same as seen on `master`), but let me know if there's something I missed or you'd like to see addressed beforehand.

**Comment by PatrickTulskie** [comment]
@codealchemy Yeah I've seen those failures too. Something about the test matrix here needs to get fixed I guess. I'll look at that and your PR and see what I can do to get a release done.

**Comment by codealchemy** [comment]
@PatrickTulskie please let me know if there's anything else I can do to help this along 🙇

**Comment by PatrickTulskie** [comment]
> @PatrickTulskie please let me know if there's anything else I can do to help this along 🙇

Will do. I'm currently neck deep in 2 different things that are taking up all of my time. I just went through and teed up this and a bunch of other things that need my review though and I'm hoping to get through them all in the next week or two when I have a little down time.

**Review by PatrickTulskie — APPROVED** [review]

**Comment by PatrickTulskie** [comment]
@jweir hey I'm prepping a new release for next week. Would you mind giving this a rebase? It's got some merge conflicts at the moment.

**Comment by PatrickTulskie** [comment]
Closing. This will get handled here: https://github.com/resque/resque-scheduler/pull/792

**Pull request closed without merging**
